<h1>Front - Base  page</h1><br>
<p><a href="<?php echo $this->getUrl('learning/index/index', ['_current' => true, '_use_rewrite' => true])?>">Index-Index Page</a></p>
<p><a href="<?php echo $this->getUrl('learning/index/base', ['_current' => true, '_use_rewrite' => true])?>">Index-Base Page</a></p>
<p><a href="<?php echo $this->getUrl('learning/front/index', ['_current' => true, '_use_rewrite' => true])?>">Front-Index Page</a></p>